# Generated by Django 2.0.3 on 2018-06-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0002_auto_20180621_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='duplicate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='telegram_watcher.DuplicateIndex'),
        ),
        migrations.AlterField(
            model_name='source',
            name='store_days',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='source',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_watcher.SourceGroup'),
        ),
    ]
