# Generated by Django 2.0.3 on 2018-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0003_auto_20180628_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='group',
        ),
        migrations.AddField(
            model_name='source',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='sources', to='telegram_watcher.SourceGroup'),
        ),
    ]
