# Generated by Django 2.0.3 on 2018-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0004_auto_20180628_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='source_groups',
            field=models.ManyToManyField(blank=True, related_name='feeds', to='telegram_watcher.SourceGroup'),
        ),
        migrations.AlterField(
            model_name='source',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='sources', to='telegram_watcher.SourceGroup'),
        ),
    ]
