# Generated by Django 2.0.3 on 2018-06-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0005_auto_20180628_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='groups',
        ),
        migrations.AddField(
            model_name='sourcegroup',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='source_groups', to='telegram_watcher.Source'),
        ),
    ]
