# Generated by Django 2.0.3 on 2018-07-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0007_auto_20180704_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram_watcher.Account')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('auth_code', models.IntegerField(blank=True, null=True, verbose_name='Auth code')),
            ],
            options={
                'verbose_name': 'Telegram Account',
            },
            bases=('telegram_watcher.account',),
        ),
        migrations.AddField(
            model_name='source',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='telegram_watcher.Account'),
        ),
    ]
