# Generated by Django 2.0.3 on 2018-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0008_auto_20180714_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
