# Generated by Django 2.0.3 on 2018-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0010_telegramaccount_phone_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='runned',
            field=models.BooleanField(default=False),
        ),
    ]
