# Generated by Django 2.0.3 on 2018-07-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0011_account_runned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='internal_id',
        ),
        migrations.AddField(
            model_name='source',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
