# Generated by Django 2.0.3 on 2018-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0013_auto_20180714_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
