# Generated by Django 2.0.3 on 2018-11-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0019_message_shared'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['date'], name='telegram_wa_date_4ca35b_idx'),
        ),
    ]
