# Generated by Django 2.0.3 on 2019-01-20 02:06

from django.db import migrations, models
import django.db.models.deletion
import telegram_watcher.models.message


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0021_messagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(storage=telegram_watcher.models.message.CDNFileStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='telegram_watcher.Message'),
        ),
    ]
