# Generated by Django 2.0.3 on 2019-01-20 19:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0022_auto_20190120_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
