# Generated by Django 2.0.3 on 2019-02-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0023_message_meta'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedmessage',
            index=models.Index(fields=['feed'], name='telegram_wa_feed_id_e1e084_idx'),
        ),
    ]
