# Generated by Django 2.0.3 on 2019-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0025_auto_20190215_1432'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['duplicate'], name='telegram_wa_duplica_698178_idx'),
        ),
    ]
