# Generated by Django 2.0.3 on 2019-02-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0026_auto_20190215_1442'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedmessage',
            index=models.Index(fields=['message'], name='telegram_wa_message_57401d_idx'),
        ),
    ]
