# Generated by Django 2.0.3 on 2019-02-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0027_auto_20190215_1445'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_4ca35b_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-date'], name='telegram_wa_date_d1338d_idx'),
        ),
    ]
