# Generated by Django 2.0.3 on 2019-04-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0031_auto_20190307_1301'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_duplica_698178_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['duplicate_id'], name='telegram_wa_duplica_698178_idx'),
        ),
    ]
