# Generated by Django 2.0.3 on 2019-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0034_auto_20190428_1731'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_76bad1_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_d1338d_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-date', 'id', 'source'], name='telegram_wa_date_7fec01_idx'),
        ),
    ]
