# Generated by Django 2.0.3 on 2019-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0035_auto_20190428_1753'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['id', '-date'], name='telegram_wa_id_bd40ce_idx'),
        ),
    ]
