# Generated by Django 2.0.3 on 2019-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0036_auto_20190428_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
