# Generated by Django 2.0.3 on 2019-04-29 07:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0037_auto_20190429_0519'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_7fec01_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_id_bd40ce_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='telegram_wa_date_3a8ff5_brin'),
        ),
    ]
