# Generated by Django 2.0.3 on 2019-04-29 07:11

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0038_auto_20190429_0706'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_3a8ff5_brin',
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date', 'id', 'source'], name='telegram_wa_date_ba0f2c_brin'),
        ),
    ]
