# Generated by Django 2.0.3 on 2019-04-29 07:18

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0039_auto_20190429_0711'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_ae4bd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_duplica_698178_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_ba0f2c_brin',
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date', 'id', 'source'], name='telegram_wa_date_3f9709_brin'),
        ),
    ]
