# Generated by Django 2.0.3 on 2019-04-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0041_auto_20190429_0745'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_3f9709_brin',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_source__add81e_idx',
        ),
    ]
