# Generated by Django 2.0.3 on 2019-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0042_auto_20190429_1059'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='telegram_wa_date_ae4bd3_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-date'], name='telegram_wa_date_d1338d_idx'),
        ),
    ]
