# Generated by Django 2.0.3 on 2019-05-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0043_auto_20190429_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='internal_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
