# Generated by Django 2.0.3 on 2019-05-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0044_auto_20190508_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('NONE', 'Select language...'), ('ENG', 'English'), ('RUS', 'Russian'), ('CHN', 'Chinese'), ('KOR', 'Korean'), ('JAP', 'Japanese')], default='eng', max_length=256),
        ),
    ]
