# Generated by Django 2.0.3 on 2019-05-27 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_watcher', '0045_auto_20190527_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='users',
            field=models.ManyToManyField(related_name='m2m_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
